{% set version = "0.9.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hexyl
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hexyl/archive/v{{ version }}.tar.gz
  sha256: 73f0dc1be1eaa1a34e3280bc1eeb4f86f34b024205fc7bf3c87d5a0bc4021a6a

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [unix]
    - {{ native }}binutils               # [win]

test:
  commands:
    - hexyl --help

about:
  home: https://github.com/sharkdp/hexyl
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A command-line hex viewer

extra:
  recipe-maintainers:
    - apcamargo
