{% set version = "0.16.0" %}

package:
  name: hexyl
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hexyl/archive/v{{ version }}.tar.gz
  sha256: 52853b4edede889b40fd6ff132e1354d957d1f26ee0c26ebdea380f8ce82cb0b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - hexyl --help

about:
  home: https://github.com/sharkdp/hexyl
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: A command-line hex viewer

extra:
  recipe-maintainers:
    - apcamargo
    - danielnachun
