{% set version = "0.10.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hexyl
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hexyl/archive/v{{ version }}.tar.gz
  sha256: 5821c0aa5fdda9e84399a5f92dbab53be2dbbcd9a7d4c81166c0b224a38624f8

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [unix]
    - {{ native }}binutils               # [win]

test:
  commands:
    - hexyl --help

about:
  home: https://github.com/sharkdp/hexyl
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A command-line hex viewer

extra:
  recipe-maintainers:
    - apcamargo
