{% set version = "0.12.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: hexyl
  version: {{ version }}

source:
  url: https://github.com/sharkdp/hexyl/archive/v{{ version }}.tar.gz
  sha256: bf3a3e8851e7bbcf01f75ae95c018faf3c9f1b7f363159d4a7459bbe11478144

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [unix]
    - {{ native }}binutils               # [win]

test:
  commands:
    - hexyl --help

about:
  home: https://github.com/sharkdp/hexyl
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: A command-line hex viewer

extra:
  recipe-maintainers:
    - apcamargo
