travis:
  secure:
    BINSTAR_TOKEN: ePLzJH0vX7+/q0a+uECEVVm+ZR5Ko6yPTWKnbWsuY8GNU+L7BZYJlH0G38Rqu98SKZGIjZMikOcjXYDawk3AmAFDWOfswZFTXY1ddG2E2QqlFxA0iuLUy48QBvmxLfCVYYLQKpBJH/EB4PXDnRY2FlHL2IR8aHE5CU2egmg0KGGZj3vdFGVueF9X2pmj0yFD+4kwXsdI/aDfYS3/8z9KqeMaBLFjPTIZ8tmxygEiwgbrFJmASAs8JYkkh/orY3uNl+AdvcVZlD/wtgWdj4JZI0/QtTurzIQNJQu2XNmECJF5cqlZbc5RS/Msiu5YLikaS9OR77LPsKlNN6IPDz4Y+ysUKdzol3IF/1Z35/iK3X8QUb/WVoPw5QdIf3pWzdMtNcUANpPFFvFNiaeEYxeBrWPIx4PCgksbBbwLV3u+1oQJkTfXZcSdKmwl3iu+D/SpAw55djSBBfv25ul7eF6dz0oflIhn02pYW7OWQrRt2Y9jJRnzuAQWc5NJakgDIb/UzVcNNRABtjBdpX6Nw9729mFtMo74DskHkiSYF1gecOdeqb0/+ZjL8+1+G2AS17dmN3eWYqGhCG6Y/wXQwd1D/hE/NmlKKLI+RYGCko5la3xPT8c4lxNB65StgmjKht44zCdT2naNZ0Xy3Al5ORqCOPe6asQ+7EbOU8fFTrj+XvA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
