travis:
  secure:
    BINSTAR_TOKEN: RQLsRS5RsVa6s0wla1kUR5O0QOWyY8VXTJ1gB89QjK3FMyc/Hl/Xt3WZaZ1jDtotN367X8g8roSvsUjbCwUhjhlvSsL5OKRE/OuzlwA8+vuWJz2v1lirjymlpzIFjNWHAkmel9c9KVZR3pTbfEl0Q9k+gkD5UaHN0QmLpqgNgIee1Pqd2RZtJs1I+gZOJUuOL8YP06sL7F6qD+zWno7wvYOzfU6gkhOaKoNRZ9GAC3q4aeD1UnB70s/uofWplJ2UvGvMdN9ZdQmK5Lb1AIF3iJOawsmK9QWwuiyqT+BbzSRpiWsuyw3C3QpGmiO9v1keR2rdUHNIr5PeSwxxORG7qlIkR/DwcipqbQaJhMGhVkFLyoxLqU91vR9kB0Q1KNzQQS+7wDtUIBOOpyO4MsSK83TwAkW9kLFrller3TSkYpBSsY+3mrA/95b3uIh1RDKUoOd56kCFFYUStEattTMkSDYOBbh+BG/68gMs+LCicye2ZNsehwa1Nz+VbR7KuRGgTZjv2JZN0u6P+xLupx1wMNnrYmfybQT/Co0piSUSptoCwvoV16cZScSnfbHAhgj3Mx5HdXyRvEn5fZeGl03Am7iLXCqnZxHLHHROvTsd46cO1+CAyj/JNN6z1TD0N1mM4FNCOG9ZC0n2X32BorQkPPW1VWPbpKHtR6z7pkTvf3k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
